language: elixir
before_install: 
  - "sudo apt-get install -y inotify-tools"
elixir: 
  - "1.7"
  - "1.8"
otp_release: 
  - "20.3"
  - "21.2"
script: 
  - "mix cotton.lint"
  - "mix coveralls.travis"